export const SET_CURRENT_USER  = 'SET_CURRENT_USER'
export const USER_SIGNED_OUT   = 'USER_SIGNED_OUT'
export const SOCKET_CONNECTED  = 'SOCKET_CONNECTED'
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS'

export const SET_SESSION_ERROR   = 'SET_SESSION_ERROR'
export const CLEAR_SESSION_ERROR = 'CLEAR_SESSION_ERROR'

export const SET_CHANGE_PASSWORD_ERRORS   = 'SET_CHANGE_PASSWORD_ERRORS'
export const CLEAR_CHANGE_PASSWORD_ERRORS = 'CLEAR_CHANGE_PASSWORD_ERRORS'

export const SET_REGISTRATIONS_ERRORS   = 'SET_REGISTRATIONS_ERRORS'
export const CLEAR_REGISTRATIONS_ERRORS = 'CLEAR_REGISTRATIONS_ERRORS'

/* START <POSTS MUTATION TYPES> */
export const SET_POSTS            = 'SET_POSTS'
export const SET_POSTS_PAGINATION = 'SET_POSTS_PAGINATION'

export const ADD_POST    = 'ADD_POST'
export const UPDATE_POST = 'UPDATE_POST'
export const DELETE_POST = 'DELETE_POST'

export const ADD_COMMENT    = 'ADD_COMMENT'
export const UPDATE_COMMENT = 'UPDATE_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'

export const UPVOTE_POST   = 'UPVOTE_POST'
export const DOWNVOTE_POST = 'DOWNVOTE_POST'
/* END <POSTS MUTATION TYPES> */

/* START <CURRENT POST MUTATION TYPES> */
export const SET_CURRENT_POST = 'SET_CURRENT_POST'

export const ADD_COMMENT_IN_CURRENT_POST    = 'ADD_COMMENT_IN_CURRENT_POST'
export const UPDATE_COMMENT_IN_CURRENT_POST = 'UPDATE_COMMENT_IN_CURRENT_POST'
export const DELETE_COMMENT_IN_CURRENT_POST = 'DELETE_COMMENT_IN_CURRENT_POST'

export const UPVOTE_POST_IN_CURRENT_POST   = 'UPVOTE_POST_IN_CURRENT_POST'
export const DOWNVOTE_POST_IN_CURRENT_POST = 'DOWNVOTE_POST_IN_CURRENT_POST'
/* END <CURRENT POST MUTATION TYPES> */

export const ADD_NOTIFICATION    = 'ADD_NOTIFICATION'
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION'

export const SET_POST_ERRORS   = 'SET_POST_ERRORS'
export const CLEAR_POST_ERRORS = 'CLEAR_POST_ERRORS'

export const HIDE_LOADING = 'HIDE_LOADING'
export const SHOW_LOADING = 'SHOW_LOADING'

export const HIDE_FETCHING_MORE = 'HIDE_FETCHING_MORE'
export const SHOW_FETCHING_MORE = 'SHOW_FETCHING_MORE'

export const SET_AUTH_VIEW = 'SET_AUTH_VIEW'

export const TOGGLE_AUTH_WIDGET        = 'TOGGLE_AUTH_WIDGET'
export const TOGGLE_NOTIFICATION_PANEL = 'TOGGLE_NOTIFICATION_PANEL'

export const ADD_ALERT    = 'ADD_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
