export const SET_CURRENT_USER  = 'SET_CURRENT_USER'
export const USER_SIGNED_OUT   = 'USER_SIGNED_OUT'
export const SOCKET_CONNECTED  = 'SOCKET_CONNECTED'
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS'

export const SET_SESSION_ERROR   = 'SET_SESSION_ERROR'
export const CLEAR_SESSION_ERROR = 'CLEAR_SESSION_ERROR'

export const SET_REGISTRATIONS_ERRORS   = 'SET_REGISTRATIONS_ERRORS'
export const CLEAR_REGISTRATIONS_ERRORS = 'CLEAR_REGISTRATIONS_ERRORS'

export const SET_POSTS = 'SET_POSTS'
export const SET_POST  = 'SET_POST'

export const SET_POST_ERRORS   = 'SET_POST_ERRORS'
export const CLEAR_POST_ERRORS = 'CLEAR_POST_ERRORS'

export const HIDE_LOADING = 'HIDE_LOADING'
export const SHOW_LOADING = 'SHOW_LOADING'

export const TOGGLE_AUTH_WIDGET = 'TOGGLE_AUTH_WIDGET'
export const TOGGLE_NOTIFICATION_PANEL = 'TOGGLE_NOTIFICATION_PANEL'
