export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const USER_SIGNED_OUT  = 'USER_SIGNED_OUT'

export const SET_SESSION_ERROR   = 'SET_SESSION_ERROR'
export const CLEAR_SESSION_ERROR = 'CLEAR_SESSION_ERROR'

export const SET_REGISTRATIONS_ERRORS   = 'SET_REGISTRATIONS_ERRORS'
export const CLEAR_REGISTRATIONS_ERRORS = 'CLEAR_REGISTRATIONS_ERRORS'

export const SET_POSTS = 'SET_POSTS'
export const SET_POST  = 'SET_POST' 

export const SET_POST_ERRORS   = 'SET_POST_ERRORS'
export const CLEAR_POST_ERRORS = 'CLEAR_POST_ERRORS'
